package uk.co.qualitycode.utils.functional;

import io.vavr.Tuple2;
import uk.co.qualitycode.utils.functional.monad.Option;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.function.Predicate;

import static uk.co.qualitycode.utils.functional.Functional.*;

/**
 * The core sequence operations expressed in terms of fold.
 * <p>
 * Also reachable as {@code Functional.inTermsOfFold}, which is kept as an alias for existing code. The constructor is
 * package-private only so that alias can extend this class.
 *
 * Implementations of the algorithms contained herein in terms of 'fold'
 * See <a href="http://en.wikipedia.org/wiki/Fold_(higher-order_function)">Fold</a>
 */
public class InTermsOfFold {

    InTermsOfFold() {
    }

    /**
     * See <a href="http://en.wikipedia.org/wiki/Map_(higher-order_function)">Map</a>
     * This is a 1-to-1 transformation. Every element in the input sequence will be transformed into an element in the output
     * sequence.
     * map: (A -> B) -> A seq -> B list
     *
     * @param f   a transformation function which takes a object of type A and returns an object, presumably related, of type B
     * @param l   a sequence to be fed into f
     * @param <T> the type of the element in the input sequence
     * @param <U> the type of the element in the output sequence
     * @return a list of type B containing the transformed values.
     * @see <a href="http://en.wikipedia.org/wiki/Fold_(higher-order_function)">Fold</a>
     */
    public static <T, U> List<T> map(final Function<? super U, ? extends T> f, final Iterable<U> l) {
        return Functional.fold((BiFunction<List<T>, U, List<T>>) (state, o2) -> {
            state.add(f.apply(o2));
            return state;
        }, l instanceof Collection<?> ? new ArrayList<>(((Collection<?>) l).size()) : new ArrayList<>(), l);
    }

    /**
     * See <a href="http://en.wikipedia.org/wiki/Filter_(higher-order_function)">Filter</a>
     *
     * @param predicate a filter function. This is passed each input element in turn and returns either true or false. If true then
     *                  the input element is passed through to the output otherwise it is ignored.
     * @param l         a sequence of objects
     * @param <T>       the type of the element in the input sequence
     * @return a list which contains zero or more of the elements of the input sequence. Each element is included only if the filter
     * function returns true for the element.
     * @see <a href="http://en.wikipedia.org/wiki/Fold_(higher-order_function)">Fold</a>
     */
    public static <T> List<T> filter(final Predicate<? super T> predicate, final Iterable<T> l) {
        return Functional.fold((BiFunction<List<T>, T, List<T>>) (ts, o) -> {
            if (predicate.test(o)) ts.add(o);
            return ts;
        }, l instanceof Collection<?> ? new ArrayList<>(((Collection<?>) l).size()) : new ArrayList<>(), l);
    }

    /**
     * The init function, not dissimilar to list comprehensions, which is used to return a new finite list whose contents are
     * determined by successive calls to the function f.
     * init: (int -> A) -> int -> A list
     *
     * @param f       generator function used to produce the individual elements of the output list. This function is called by init
     *                with the unity-based position of the current element in the output list being produced. Therefore, the first time
     *                f is called it will receive a literal '1' as its argument; the second time '2'; etc.
     * @param howMany the number of elements in the output list
     * @param <A>     the type of the element in the output sequence
     * @return a list of 'howMany' elements of type 'T' which were generated by the function 'f'
     * @see <a href="http://en.wikipedia.org/wiki/Fold_(higher-order_function)">Fold</a>
     */
    public static <A> List<A> init(final Function<Integer, ? extends A> f, final int howMany) {
        return Functional.unfold(a -> a <= howMany ? Option.of(new Tuple2<>(f.apply(a), a + 1)) : Option.none(), 1);
    }
}
